"""Basic docx2shelf plugin template.

Generated by `docx2shelf plugins create <name> --template basic`.
Implements one of each hook type as a no-op so you can fill in real logic.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List

from docx2shelf.plugins import (
    BasePlugin,
    MetadataResolverHook,
    PluginHook,
    PostConvertHook,
    PreConvertHook,
)


class BasicPreProcessor(PreConvertHook):
    """Run before DOCX → HTML conversion. Modify or replace the source file."""

    def process_docx(self, docx_path: Path, context: Dict[str, Any]) -> Path:
        # Inspect / rewrite docx_path here. Return the original or a new path.
        return docx_path


class BasicPostProcessor(PostConvertHook):
    """Run on the converted HTML before EPUB assembly."""

    def transform_html(self, html_content: str, context: Dict[str, Any]) -> str:
        # Modify html_content here. Return the transformed string.
        return html_content


class BasicMetadataResolver(MetadataResolverHook):
    """Inject or override metadata fields (title, author, subjects, etc.)."""

    def resolve_metadata(
        self, metadata: Dict[str, Any], context: Dict[str, Any]
    ) -> Dict[str, Any]:
        # Mutate or replace fields in `metadata`, then return it.
        return metadata


class BasicTemplatePlugin(BasePlugin):
    """Wires the three hooks above into the docx2shelf plugin manager."""

    def __init__(self) -> None:
        super().__init__(name="basic_template", version="0.1.0")

    def get_hooks(self) -> Dict[str, List[PluginHook]]:
        return {
            "pre_convert": [BasicPreProcessor()],
            "post_convert": [BasicPostProcessor()],
            "metadata_resolver": [BasicMetadataResolver()],
        }
