apiVersion: v1
kind: ConfigMap
metadata:
  name: docx2shelf-config
  labels:
    app: docx2shelf
data:
  app.yaml: |
    # Docx2Shelf Application Configuration
    server:
      host: "0.0.0.0"
      port: 8080
      health_port: 8081
      workers: 4
      max_request_size: 100MB
      request_timeout: 300s

    conversion:
      max_concurrent_jobs: 10
      temp_dir: "/tmp/docx2shelf"
      cleanup_interval: 300s
      max_file_size: 50MB

    monitoring:
      enabled: true
      metrics_enabled: true
      health_checks_enabled: true
      prometheus_metrics: true
      log_level: "INFO"

    security:
      enable_cors: true
      cors_origins: ["*"]
      rate_limiting:
        enabled: true
        requests_per_minute: 60
        burst_size: 10

    plugins:
      enable_hot_reload: true
      sandbox_enabled: true
      resource_limits:
        max_memory_mb: 256
        max_cpu_percent: 50
        max_execution_time_seconds: 30

  logging.yaml: |
    version: 1
    formatters:
      default:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      json:
        format: '{"timestamp": "%(asctime)s", "logger": "%(name)s", "level": "%(levelname)s", "message": "%(message)s", "module": "%(module)s", "function": "%(funcName)s", "line": %(lineno)d}'
    handlers:
      console:
        class: logging.StreamHandler
        level: INFO
        formatter: json
        stream: ext://sys.stdout
    loggers:
      docx2shelf:
        level: INFO
        handlers: [console]
        propagate: false
    root:
      level: INFO
      handlers: [console]