apiVersion: apps/v1
kind: Deployment
metadata:
  name: docx2shelf
  labels:
    app: docx2shelf
    version: v1.2.6
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docx2shelf
  template:
    metadata:
      labels:
        app: docx2shelf
        version: v1.2.6
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: docx2shelf
        image: ghcr.io/docx2shelf/docx2shelf:v1.2.6
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        env:
        - name: DOCX2SHELF_WEB_PORT
          value: "8080"
        - name: DOCX2SHELF_HEALTH_PORT
          value: "8081"
        - name: DOCX2SHELF_LOG_LEVEL
          value: "INFO"
        - name: DOCX2SHELF_MONITORING_ENABLED
          value: "true"
        - name: DOCX2SHELF_METRICS_ENABLED
          value: "true"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: health
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: health
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        startupProbe:
          httpGet:
            path: /health/startup
            port: health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
        volumeMounts:
        - name: temp-storage
          mountPath: /tmp/docx2shelf
        - name: config
          mountPath: /app/config
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop:
            - ALL
      volumes:
      - name: temp-storage
        emptyDir:
          sizeLimit: 5Gi
      - name: config
        configMap:
          name: docx2shelf-config
      securityContext:
        fsGroup: 1000
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - docx2shelf
              topologyKey: kubernetes.io/hostname
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1