apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docx2shelf.fullname" . }}
  labels:
    {{- include "docx2shelf.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "docx2shelf.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "docx2shelf.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "docx2shelf.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.server.port }}
              protocol: TCP
            - name: health
              containerPort: {{ .Values.config.server.health_port }}
              protocol: TCP
          env:
            - name: DOCX2SHELF_WEB_PORT
              value: {{ .Values.config.server.port | quote }}
            - name: DOCX2SHELF_HEALTH_PORT
              value: {{ .Values.config.server.health_port | quote }}
            - name: DOCX2SHELF_LOG_LEVEL
              value: {{ .Values.config.monitoring.log_level | quote }}
            - name: DOCX2SHELF_MONITORING_ENABLED
              value: {{ .Values.config.monitoring.enabled | quote }}
            - name: DOCX2SHELF_METRICS_ENABLED
              value: {{ .Values.config.monitoring.metrics_enabled | quote }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.health.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.health.liveness.path }}
              port: health
            initialDelaySeconds: {{ .Values.health.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.health.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.health.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.health.liveness.failureThreshold }}
          {{- end }}
          {{- if .Values.health.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.health.readiness.path }}
              port: health
            initialDelaySeconds: {{ .Values.health.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.health.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.health.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.health.readiness.failureThreshold }}
          {{- end }}
          {{- if .Values.health.startup.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.health.startup.path }}
              port: health
            initialDelaySeconds: {{ .Values.health.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.health.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.health.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.health.startup.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}